apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orders-service
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: 74714672583.dkr.ecr.us-east-1.amazonaws.com/oasis-ats-dev-order-service:0.1.0-440be74
        envFrom:
        - configMapRef:
            name: orders-service
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 256Mi
  strategy:
    canary:
      analysis:
        startingStep: 1   
        templates:
        - templateName: istio-success-rate
        args:             
        - name: service 
          value: orders-service
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      trafficRouting:
        istio:
          virtualService:
            name: orders-service-vsvc
            routes:
            - primary
          destinationRule:
            name: orders-service-destrule    # required
            canarySubsetName: canary  # required
            stableSubsetName: stable  # required
      steps:
      - setWeight: 10
      - pause: {}         # pause indefinitely
      - setWeight: 20
      - pause: {duration: 20s}
      - setWeight: 30
      - pause: {duration: 20s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 50
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 70
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
      - setWeight: 90
      - pause: {duration: 20s}
