{{- if .Values.Deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.name }}
spec:
  replicas: {{ default "1" .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.name }}
      version: {{ default "v1" .Values.Deployment.version }}
{{- if eq .Values.Deployment.strategy.type "RollingUpdate" }}
  strategy:
    rollingUpdate:
      maxSurge: {{  .Values.Deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{  .Values.Deployment.strategy.rollingUpdate.maxUnavailable }}
{{- else if eq .Values.Deployment.strategy.type "Recreate" }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.name }}
        version: {{ default "v1" .Values.Deployment.version }}
    spec:
      containers:
      - name: {{ .Values.Deployment.name }}
        image: "{{ .Values.Deployment.imageRepository }}:{{ .Values.Deployment.imageTag }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.Deployment.configMap }}
        resources:
          limits:
            cpu: {{ default "1" .Values.Deployment.limitCpu }}
            memory: {{ default "512Mi" .Values.Deployment.limitMem }}
          requests:
            cpu: {{ default "0.5" .Values.Deployment.requestCpu }}
            memory: {{ default "256Mi" .Values.Deployment.requestMem }}
{{- if .Values.Deployment.expose.enabled }}
        ports:
{{- range .Values.Deployment.expose.ports }}
        - containerPort: {{ .port }}
{{- end }}
{{- end }}
{{- if .Values.Deployment.healthCheck.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.Deployment.healthCheck.path }}  
            port: {{ .Values.Deployment.healthCheck.port }} 
          initialDelaySeconds: 20
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: {{ .Values.Deployment.healthCheck.path }} 
            port: {{ .Values.Deployment.healthCheck.port }} 
          initialDelaySeconds: 20
          periodSeconds: 30

{{- end }}
{{- end }}
