{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.Deployment.name }}
spec:
  minReplicas: {{ default 1 .Values.hpa.minReplicas }}
  maxReplicas: {{ default 10 .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.Deployment.name }}
  targetCPUUtilizationPercentage: {{ default 60 .Values.hpa.cpuTarget }}
{{- end }}