{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Deployment.name }}
  labels:
    app: {{ .Values.Deployment.name }}
    name: {{ .Values.Deployment.name }}
    version: {{ default "v1" .Values.Deployment.version }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.Deployment.healthCheck.path }}
spec:
  type: {{ default "ClusterIP" .Values.service.serviceType }}
  ports:
{{- range .Values.Deployment.expose.ports }}
  - name: "tcp-{{ .port }}"
    port: {{ .port }}
{{- end }}
  selector:
    app: {{ .Values.Deployment.name }}
{{- end }}
